/**
 * Single source of truth for site-wide identity, navigation and SEO defaults.
 * Everything that appears in more than one place lives here.
 */

/** Production origin. No trailing slash, no `www` — this is the canonical host. */
const PRODUCTION_URL = 'https://rfpsoftwareguide.com';

/**
 * Every absolute URL on the site derives from this: canonicals, `metadataBase`,
 * Open Graph and Twitter tags, JSON-LD, the sitemap, robots.txt and the RSS feed.
 *
 * `NEXT_PUBLIC_SITE_URL` overrides it so preview and staging deployments emit
 * their own origin instead of claiming the production one. It is read at build
 * time; a trailing slash is stripped so callers can always append a path.
 */
function resolveSiteUrl(): string {
  const configured = process.env.NEXT_PUBLIC_SITE_URL?.trim();
  if (!configured) return PRODUCTION_URL;
  return configured.replace(/\/+$/, '');
}

export const siteConfig = {
  name: 'RFP Software Guides',
  shortName: 'RFP Guides',
  url: resolveSiteUrl(),
  tagline: 'The Complete Resource Hub for RFP Software',
  description:
    'Independent, vendor-neutral guides on buying, evaluating, comparing and implementing RFP software — plus templates, checklists and a working glossary.',
  locale: 'en_US',
  language: 'en',
  publisher: 'RFP Software Guides',
  foundingYear: 2023,
  twitterHandle: '@rfpguides',
  /** Route generated by app/opengraph-image.tsx — a real 1200x630 PNG. */
  ogImage: '/opengraph-image',
  logo: '/images/logo-mark.svg',
  contactEmail: 'editors@rfpsoftwareguide.com',
} as const;

/**
 * Hostname without scheme or `www`, for display in UI and social cards.
 * Derived rather than hard-coded so it follows `siteConfig.url` automatically.
 */
export function displayDomain(): string {
  return siteConfig.url.replace(/^https?:\/\//, '').replace(/^www\./, '');
}

export type NavItem = {
  label: string;
  href: string;
  description?: string;
};

export const primaryNav: NavItem[] = [
  { label: 'Home', href: '/', description: 'Start here' },
  {
    label: 'Guides',
    href: '/guides',
    description: 'Long-form buying and evaluation guides',
  },
  {
    label: 'Blog',
    href: '/blog',
    description: 'Analysis, trends and product thinking',
  },
  {
    label: 'Resources',
    href: '/resources',
    description: 'Templates, checklists and glossary',
  },
  { label: 'About', href: '/about', description: 'Our editorial standards' },
];

export const footerNav: { title: string; items: NavItem[] }[] = [
  {
    title: 'Guides',
    items: [
      { label: 'How to Buy RFP Software', href: '/guides/how-to-buy-rfp-software' },
      {
        label: 'What to Look For in RFP Software',
        href: '/guides/things-to-look-for-in-rfp-software',
      },
      {
        label: 'Compliance Matrix for Selection',
        href: '/guides/compliance-matrix-to-select-rfp-software',
      },
      {
        label: 'How to Find RFP Software Vendors',
        href: '/guides/how-to-find-rfp-software-vendors',
      },
    ],
  },
  {
    title: 'Blog',
    items: [
      {
        label: 'Top RFP Software Differentiators',
        href: '/blog/top-rfp-software-differentiators',
      },
      { label: 'What Is AI RFP Software?', href: '/blog/what-is-ai-rfp-software' },
      { label: 'Best AI Proposal Tools', href: '/blog/best-ai-proposal-tools' },
      {
        label: 'The Future of AI in RFP Responses',
        href: '/blog/future-of-ai-in-rfp-responses',
      },
    ],
  },
  {
    title: 'Resources',
    items: [
      { label: 'All resources', href: '/resources' },
      { label: 'Templates', href: '/resources#templates' },
      { label: 'Buying checklists', href: '/resources#checklists' },
      { label: 'Glossary', href: '/resources#glossary' },
      { label: 'Compliance resources', href: '/resources#compliance' },
    ],
  },
  {
    title: 'Site',
    items: [
      { label: 'About', href: '/about' },
      { label: 'Editorial standards', href: '/about#editorial-standards' },
      { label: 'RSS feed', href: '/rss.xml' },
      { label: 'Sitemap', href: '/sitemap.xml' },
    ],
  },
];

export const socialLinks = [
  { label: 'LinkedIn', href: 'https://www.linkedin.com/', icon: 'linkedin' as const },
  { label: 'X', href: 'https://x.com/', icon: 'x' as const },
  { label: 'YouTube', href: 'https://www.youtube.com/', icon: 'youtube' as const },
  { label: 'RSS', href: '/rss.xml', icon: 'rss' as const },
];

/** Absolute URL helper — used by metadata, JSON-LD, sitemap and RSS. */
export function absoluteUrl(path = '/'): string {
  if (path.startsWith('http')) return path;
  const clean = path.startsWith('/') ? path : `/${path}`;
  return `${siteConfig.url}${clean === '/' ? '' : clean}`;
}

/**
 * Absolute URL of a page's social card.
 *
 * Guides and blog posts render their own titled card via an `opengraph-image`
 * file in their route segment; everything else inherits the site default.
 */
export function ogImageUrl(path = '/'): string {
  const hasOwnCard = /^\/(guides|blog)\/[^/]+$/.test(path);
  return absoluteUrl(hasOwnCard ? `${path}/opengraph-image` : siteConfig.ogImage);
}
